apiVersion: v2
name: kubernetes-event-exporter
description: A Helm chart for kubernetes-event-exporter without Bitnami dependencies
type: application
version: 0.1.6
appVersion: "v1.7"
license: MIT
keywords:
  - kubernetes
  - events
  - monitoring
  - logging
home: https://github.com/resmoio/kubernetes-event-exporter
sources:
  - https://github.com/resmoio/kubernetes-event-exporter
maintainers:
  - name: Niklas Hoefflin (itakurah)
    url: https://github.com/itakurah
