{{- if .Values.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  namespace: {{ include "kubernetes-event-exporter.namespace" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubernetes-event-exporter.selectorLabels" . | nindent 6 }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
{{- end }}

