apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
rules:
{{- toYaml .Values.rbac.rules | nindent 0 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubernetes-event-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  namespace: {{ include "kubernetes-event-exporter.namespace" . }}
