apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  namespace: {{ include "kubernetes-event-exporter.namespace" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }}
